# Generated by Django 4.2.15 on 2026-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0035_update_trace_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiegeCreances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(blank=True, help_text="URL de l'application VDL Créances", max_length=255, verbose_name='URL')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='Clé API')),
                ('users', models.ManyToManyField(blank=True, related_name='+', related_query_name='+', to='base.apiuser')),
            ],
            options={
                'verbose_name': 'Connecteur Liege Creances',
            },
        ),
    ]
